### ISSUE TITLE
Release an NPM package for Postject

### ISSUE THREAD

**Issue by jviotti** [postmanlabs/postject#14]

**Comment by RaisinTen** [comment]
I'm taking this up because David is asleep now and I'm up and this is the highest priority task now.
FWIW, published in https://www.npmjs.com/package/postject!
Will send a PR to do this on CI.

**Comment by RaisinTen** [comment]
Who should we add to owners? Currently both my postman and my primary npm accounts show up when I do `npm owner ls`. I've also sent an invite to @dsanders11. Should we add everyone in the `postman` org to owners?

**Comment by RaisinTen** [comment]
Now the Postject CircleCI project has an env var named `NPM_TOKEN` which contains my primary npm account auth token that shows up in `~/.npmrc` when I log in.

**Comment by dsanders11** [comment]
> Should we add everyone in the postman org to owners?

I don't think that's necessary, let's just add members from our team.

**Comment by RaisinTen** [comment]
In that case, maybe we give access to people who need it, when they ask for it?

**Comment by RaisinTen** [comment]
Postject has been officially published to NPM, closing!
