### ISSUE TITLE
Investigate alpine build failures

### ISSUE THREAD

**Issue by robertgzr** [postmanlabs/postject#31]
https://github.com/postmanlabs/postject/pull/8#issuecomment-1256811594
https://app.circleci.com/pipelines/github/postmanlabs/postject/43/workflows/1d1de15e-3b3b-48d3-982c-4df45f8947c6/jobs/249

**Comment by robertgzr** [comment]
looks like https://github.com/emscripten-core/emsdk/issues/897

```
/emsdk # ldd /emsdk/upstream/bin/clang
	/lib64/ld-linux-x86-64.so.2 (0x7fa3aef0d000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fa3aef0d000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7fa3aef0d000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fa3aef0d000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fa3aef0d000)
	libz.so.1 => /lib/libz.so.1 (0x7fa3a8fb7000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fa3a8f9e000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fa3aef0d000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /emsdk/upstream/bin/clang)
Error relocating /emsdk/upstream/bin/clang: mallinfo: symbol not found
Error relocating /emsdk/upstream/bin/clang: backtrace: symbol not found
Error relocating /emsdk/upstream/bin/clang: backtrace_symbols_fd: symbol not found
Error relocating /emsdk/upstream/bin/clang: strtoll_l: symbol not found
Error relocating /emsdk/upstream/bin/clang: strtoull_l: symbol not found
```

we can try building it from source I guess, there used to be a package for alpine, but it was dropped from the testing repo due to lack of maintenance: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/23041

which might be an indicator of how smooth the from source approach would be...

otherwise the approach linked in the emsdk issue (installing glibc in alpine) would probably work, but I don't see the point

**Comment by dsanders11** [comment]
Agreed that it's probably not worth the effort to get building on Alpine, we can consider that an unsupported platform for building. Will look into refactoring the tests so we can still test on Alpine without building there.
